# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  clang_format_lint:
    description: "Perform clang-format linting"
    parameters:
      source:
        type: string
      extensions:
        type: string
      style:
        type: string
        default: "file"
    steps:
      - run: echo "TODO"

  checkout_full:
    description: "Checkout the whole package of MMDeploy"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  lint:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.7.4
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Install pre-commit hook
          command: |
            sudo apt-add-repository ppa:brightbox/ruby-ng -y
            sudo apt-get update
            sudo apt-get install -y ruby2.7
            pip install pre-commit
            pre-commit install
      - run:
          name: Linting
          command: pre-commit run --all-files
      - clang_format_lint:
          name: Format c/cuda codes with clang-format
          source: csrc
          extensions: h,c,cpp,hpp,cu,cuh
          style: file
      - run:
          name: Check docstring coverage
          command: |
            pip install interrogate
            interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 80 mmdeploy

  # build mmdeploy using its CPU Dockerfile
  test_cpu:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: large
    working_directory: ~/
    steps:
      - checkout_full
#      - run:
#          name: Build mmdeploy-cpu docker image
#          command: |
#            cd mmdeploy
#            docker build docker/CPU/ -t mmdeploy:cpu


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  pr_stage_test:
    jobs:
      - lint
      - test_cpu:
          name: build cpu version on ubuntu platform
